name: build-windows-exe
on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyqt5 opencv-python numpy
      - name: Build exe
        run: pyinstaller --noconfirm --onefile --windowed --name "Dental Mask Editor" segmentprog.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MaskEditor
          path: dist/**
          if-no-files-found: error
          retention-days: 30